version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo instalando dependencias do projeto
      - npm install
  build:
    commands:
      - echo Build iniciado em `date`
  post_build:
    commands:
      - echo Build finalizado em `date`
artifacts:
  files:
    - '*/'